version: "3.2"
services:
  database:
    container_name: soccerdb-container
    image: mysql:8.0.22
    volumes:
      - ~/docker/mysql/demo/etc/mysql/conf.d:/etc/mysql/conf.d:ro
      - ~/docker/mysql/demo/var/lib/mysql:/var/lib/mysql
      - ~/docker/mysql/demo/var/log/mysql:/var/log/mysql
    environment:
      - MYSQL_DATABASE=soccerdb
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - "3306:3306"

